name: Deploy React App5

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Auth Email
        run: git config --global user.email "mdsamimakhter2001@gmail.com"
      - name: Auth User
        run: git config --global user.name "imdsamimakhter"
      
      - name: Build and deploy
        run: |
          npm install gh-pages --save-dev
          npm run build
          npm run deploy
        env:
          REACT_APP_ENV: production
